version: '3.3'

services:
  app:
    build: .
    volumes:
      - .:/app
    restart: always
    ports:
      - "50051:50051"
      - "4000:4000"
    environment:
      DB_HOST: db
    depends_on:
      - db
    command:
      - "./entrypoint.sh"
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgres-data: {}
